In [ ]:
# Step -1 ( Import basic libraries )
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
# Step - 2 ( Load the data )
df=pd.read_csv("customer_churn.csv")
df

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,...,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,No
7039,2234-XADUH,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,No
7040,4801-JZAZL,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,8361-LTMKD,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,Yes
7042,3186-AJIEK,Male,0,No,No,66,Yes,No,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No

In [ ]:
# Step - 3 ( EDA - Exploratory Data Analysis )

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB

In [ ]:
# Check for Null values / Missing values
df.isnull().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [ ]:
# Check for Null values / Missing values
df.isna().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [ ]:
# Check for duplicate values
print(df.duplicated().sum())

0

**we dont need to remove outliers in Tree algorithms because these also are robust to outliers**

In [ ]:
# Step - 4 ( Data Pre-processing )

# Remove the customer id extra columns
df.drop(columns=["customerID"], inplace=True)

In [ ]:
# Encoding - Convert Categorical values to Numerical values
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
for i in df.columns:
  if df[i].dtype=="object": # If any column is having data type object , Apply Label Encoding to it
    df[i] = le.fit_transform(df[i])

In [ ]:
df  # Clean data ready for model building

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,0,0,1,0,1,0,1,0,0,2,0,0,0,0,0,1,2,29.85,2505,0
1,1,0,0,0,34,1,0,0,2,0,2,0,0,0,1,0,3,56.95,1466,0
2,1,0,0,0,2,1,0,0,2,2,0,0,0,0,0,1,3,53.85,157,1
3,1,0,0,0,45,0,1,0,2,0,2,2,0,0,1,0,0,42.30,1400,0
4,0,0,0,0,2,1,0,1,0,0,0,0,0,0,0,1,2,70.70,925,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,1,0,1,1,24,1,2,0,2,0,2,2,2,2,1,1,3,84.80,1597,0
7039,0,0,1,1,72,1,2,1,0,2,2,0,2,2,1,1,1,103.20,5698,0
7040,0,0,1,1,11,0,1,0,2,0,0,0,0,0,0,1,2,29.60,2994,0
7041,1,1,1,0,4,1,2,1,0,0,0,0,0,0,0,1,3,74.40,2660,1
7042,1,0,0,0,66,1,0,1,2,0,2,2,2,2,2,1,0,105.65,5407,0

In [ ]:
# Step - 5 ( Data Splitting for Model Building )

x= df.drop("Churn", axis=1)  # Independent variables
y= df["Churn"]  # Dependent variables

# Divide my data into training and testing data
from sklearn.model_selection import train_test_split
x_train , x_test , y_train , y_test = train_test_split( x , y , test_size=0.2 , random_state=42 )

In [ ]:
# Step - 6 ( Model Training and Testing )
from sklearn.ensemble import RandomForestClassifier

model_1 = RandomForestClassifier()

# Train the model
model_1.fit(x_train , y_train)

# Ask the model to predict
y_pred = model_1.predict(x_test)

# Evalaute the performance by comparing predicted values with Actual values
from sklearn.metrics import *

print("Accuracy score of the model is :", accuracy_score(y_pred , y_test)*100)

Accuracy score of the model is : 79.63094393186657

In [ ]:
# Step - 6 ( Model Training and Testing )
from sklearn.ensemble import RandomForestClassifier

model_1 = RandomForestClassifier(n_estimators=200 , criterion="entropy" , max_depth=10 , min_samples_leaf=5 , min_samples_split=5)

# Train the model
model_1.fit(x_train , y_train)

# Ask the model to predict
y_pred = model_1.predict(x_test)

# Evalaute the performance by comparing predicted values with Actual values
from sklearn.metrics import *

print("Accuracy score of the model is :", accuracy_score(y_pred , y_test)*100)

Accuracy score of the model is : 80.97941802696948

In [ ]:
paramaters_grid={ "n_estimators":[50,100,150,200] ,"criterion":["gini","entropy"] ,"max_depth":[5,7,8,9,10,11,12,13,14,15,20] ,"min_samples_leaf":[1,5,10,15,20] , "min_samples_split":[1,5,10,15,20] }

from sklearn.model_selection import GridSearchCV
model=RandomForestClassifier()

grid_search = GridSearchCV( estimator=model , param_grid=paramaters_grid)
grid_search.fit(x_train , y_train)
print("Best hyperparamater values are:", grid_search.best_params_)

In [ ]:
from sklearn.ensemble import RandomForestClassifier

model_1 = RandomForestClassifier(n_estimators=100 , criterion="gini" , max_depth=10 , min_samples_leaf=5 , min_samples_split=5)

# Train the model
model_1.fit(x_train , y_train)

# Ask the model to predict
y_pred = model_1.predict(x_test)

# Evalaute the performance by comparing predicted values with Actual values
from sklearn.metrics import *

print("Accuracy score of the model is :", accuracy_score(y_pred , y_test)*100)

Accuracy score of the model is : 81.12136266855926